name: "secrets test"

on:
  push:

jobs:
  build_windows:
    name: "Test some secrets"
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    - name: "Peek at some secrets via PowerShell"
      run: "Get-ChildItem env:"
      env:
        SECRETS_1: "${{ secrets.SECRETS_1 }}"
        SECRETS_2: "${{ secrets.SECRETS_2 }}"
    - name: "Peek at some secrets via Bash"
      run: echo $SECRETS_1 $SECRETS_2
      env:
        SECRETS_1: "${{ secrets.SECRETS_1 }}"
        SECRETS_2: "${{ secrets.SECRETS_2 }}"
      shell: bash